### ISSUE TITLE
No longer works on macOS 13.4.1 - can't find cxxabi.h

### ISSUE THREAD

**Issue by jamsden** [kunitoki/popsicle#16]
Running the sample program gives: /Users/cx/software/ROOT/build/include/TClassEdit.h:29:10: fatal error: 'cxxabi.h' file not found
#include <cxxabi.h>

Building locally didn't fix it either.

I see /usr/local/include/4.8.4/cxxabi.h on my machine, and tried putting that in the CPLUS_INLCUDE_PATH, but not change.

**Comment by kunitoki** [comment]
I suspect we need to bump cppyy

**Comment by kunitoki** [comment]
I tried bump to latest cppyy in master (no release yet) and was able to run some examples but some others fail or crash
